### ISSUE TITLE
Facebook mediation is crashing on Android 4.x and 5.x devices

### ISSUE THREAD

**Issue by mnuetzmann** [mopub/mopub-android-mediation#278] opened 2020-08-01 02:23 UTC
1. **What is the issue?**
    Interstitial mediation with facebook is crashing on Android 4 & 5 devices

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x ] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Interstitial
    * **Platform** (*Android, iOS, Unity*)
        > Android
    * **MoPub SDK Version**
        > com.mopub:mopub-sdk-fullscreen:5.13.1@aar

    * **Mediation SDK Name & Version**
        > com.facebook.android:audience-network-sdk:5.10.0

    * **Mediation Adapter Version**
        > com.mopub.mediation:facebookaudiencenetwork:5.10.0.0

    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > 83d098ab0b794e88a7ded49ac5c10ca8

    * **Device model and OS Version**
        > Galaxy Tab A6, Motorola G  Android 5

    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Mediation sdk crashes

    * **Expected behavior** (if known)
        > Don't Crash

    * **Evidence** (if available)
        > 
com.facebook.ads.redexgen.X.XF.A00 (XF.java:57034)
com.facebook.ads.redexgen.X.XF.<init> (XF.java:57030)
com.facebook.ads.redexgen.X.XC.A01 (XC.java:56918)
com.facebook.ads.redexgen.X.Xb.A01 (Xb.java:57328)
com.facebook.ads.redexgen.X.Xb.A0B (Xb.java:57360)
com.facebook.ads.redexgen.X.5p.getBidderToken (5p.java:13647)
com.facebook.ads.BidderTokenProvider.getBidderToken (BidderTokenProvider.java:28)
com.mopub.mobileads.FacebookAdapterConfiguration$1.run (FacebookAdapterConfiguration.java:123)
java.lang.Thread.run (Thread.java:818)

**Comment by mnuetzmann** [comment] 2020-08-01 02:26
Another crash log

com.facebook.ads.redexgen.X.8O.A00 (8O.java:17319)
com.facebook.ads.redexgen.X.XF.A00 (XF.java:57034)
com.facebook.ads.redexgen.X.XF.<init> (XF.java:57030)
com.facebook.ads.redexgen.X.XC.A01 (XC.java:56918)
com.facebook.ads.redexgen.X.Xb.A01 (Xb.java:57328)
com.facebook.ads.redexgen.X.Xb.A0B (Xb.java:57360)
com.facebook.ads.redexgen.X.5p.getBidderToken (5p.java:13647)
com.facebook.ads.BidderTokenProvider.getBidderToken (BidderTokenProvider.java:28)
com.mopub.mobileads.FacebookAdapterConfiguration$1.run (FacebookAdapterConfiguration.java:123)
java.lang.Thread.run (Thread.java:818)

**Comment by mnuetzmann** [comment] 2020-08-01 02:27
We are getting these crashes in several of our apps with the latest MoPub sdk version

**Comment by chauduyphanvu** [comment] 2020-08-01 02:34
@mnuetzmann, this is a duplicate of https://github.com/mopub/mopub-android-mediation/issues/273 and has been addressed in https://github.com/mopub/mopub-android-mediation/commit/9a7ceb944b421096e6bfa3d9f4af6a082073f3be. Please upgrade and let us know if you continue seeing the crash!

Vu Chau
MoPub Team

**Closed by chauduyphanvu** 2020-08-01 02:34 UTC
