### ISSUE TITLE
Unity Android Can not watch Admob's Rewarded Video

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-android-mediation#174] opened 2019-06-14 01:44 UTC
1. **What is the issue?**
    >Unity Android Can not watch Admob's Rewarded Video. 
    >I saw the "Didn't find class java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/rewarded/RewardedAdLoadCallback;
.....
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.rewarded.RewardedAdLoadCallback" 
.....
 in the  log.
and I saw import com.google.android.gms.ads.rewarded.RewardedAdLoadCallback; in code.
where is it ? Should I download some things, and copy them to my Unity project ?
Please help me. Thanks !

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Rewarded Video
    * **Platform** (*Android, iOS, Unity*)
        > Android Unity
    * **MoPub SDK Version**
        > 5.5
    * **Mediation SDK Name & Version**
        > Provide the data here
    * **Mediation Adapter Version**
        > mopub-admob-adapters-17.2.1.0.aar
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > mopub:d4334ab87913499abdc598438cdb7fbc        
        > admob:ca-app-pub-2920699096839371~8732331210
    * **Device model and OS Version**
        > Android 7.1.1
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        >java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/rewarded/RewardedAdLoadCallback;
.....
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.rewarded.RewardedAdLoadCallback" 
.....

**Comment by chauduyphanvu1** [comment] 2019-06-14 01:48
This is a duplicate of issue https://github.com/mopub/mopub-android-mediation/issues/171.

**Closed by chauduyphanvu1** 2019-06-14 01:48 UTC
