### ISSUE TITLE
Can not use SDK Manager in Unity

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-android-mediation#176] opened 2019-06-20 02:09 UTC
1. **What is the issue?**
    > I import Mopub SDK into Unity, open SDK Manager's window. I can not see any things.
MoPub SDK Version : 5.5.0
Unity Version : 5.6.6f2 both in Win10 and Mac Mojave 10.14.5

I have viewed some code in MoPubSDKManager.cs
`private const string manifestURL = "https://mopub-mediation.firebaseio.com/.json";
private const string stagingURL = "https://mopub-mediation-staging.firebaseio.com/.json";`

![1](https://user-images.githubusercontent.com/17681628/59813115-e2943880-9342-11e9-8c71-51310c1e6c6b.png)

But I can not  visit it by my Chrome. I review other code, I think if it can not visit these url then It can not show infomation in SDK's window.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Provide the data here
    * **Platform** (*Android, iOS, Unity*)
        > Provide the data here
    * **MoPub SDK Version**
        > 
    * **Mediation SDK Name & Version**
        > Provide the data here
    * **Mediation Adapter Version**
        > Provide the data here
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Provide the data here
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.

**Comment by chauduyphanvu1** [comment] 2019-06-20 14:09
@GITHUB243884919, thanks for letting us know about that behavior! 

Could you confirm that you are based in China? We use Firebase and a few other services from Google to power the SDK Manager, and we have heard reports from other China-based publishers that those services are not accessible behind the Great Firewall. If that is the case, then I would say it is an "expected behavior" that you are not seeing any data displayed in the SDK Manager popup window.

Let me discuss with the rest of the team on what we can do to provide alternatives here. Meanwhile, I know that you are integrating manually, so let us know if you see any issues.

Vu Chau
MoPub SDK Team

**Comment by GITHUB243884919** [comment] 2019-06-20 14:58
> @GITHUB243884919, thanks for letting us know about that behavior!
> 
> Could you confirm that you are based in China? We use Firebase and a few other services from Google to power the SDK Manager, and we have heard reports from other China-based publishers that those services are not accessible behind the Great Firewall. If that is the case, then I would say it is an "expected behavior" that you are not seeing any data displayed in the SDK Manager popup window.
> 
> Let me discuss with the rest of the team on what we can do to provide alternatives here. Meanwhile, I know that you are integrating manually, so let us know if you see any issues.
> 
> Vu Chau
> MoPub SDK Team
Thank you~ 
Oh, I am in China. I use VPN, I can visit www.google.com, www.facebook.com .... If I do not use VPN then I can not visit these web sit.

**Comment by chauduyphanvu1** [comment] 2019-06-20 15:00
Could you confirm if the SDK Manager works when you have the VPN enabled?

**Comment by GITHUB243884919** [comment] 2019-06-20 15:11
> Could you confirm if the SDK Manager works when you have the VPN enabled?

Yes. but I heard that these are some  different type VPN in China, Maybe my VPN can let me visit www.facebook.com, but it can not let me visit url of SDK Manager's need.

**Comment by chauduyphanvu1** [comment] 2019-06-21 14:35
@GITHUB243884919, thank you for the confirmation. We'll check what we can do to support this use case.

**Comment by GITHUB243884919** [comment] 2019-06-26 01:27
> @GITHUB243884919, thank you for the confirmation. We'll check what we can do to support this use case.

hi，I can use SDK Manager now。 2 step
1.Use VPN
2.Set VPN is Shadowsocks mode and not PAC mode。 We name this "VPN全局模式" in China.
![微信图片_20190626092308](https://user-images.githubusercontent.com/17681628/60144183-0e586800-97f4-11e9-8c74-f52db2cf3cdc.jpg)

I will create a new project and use SDK Manager try again.
If I have new question I would commit new issue.
I can see your head Icon:) Are you a Chinese?

**Comment by chauduyphanvu** [comment] 2019-06-26 15:33
Glad to see the VPN solution helps you use the SDK Manager now! I'm closing this issue since it's working as expected.

**Closed by chauduyphanvu** 2019-06-26 15:33 UTC
