### ISSUE TITLE
Admob Mediation Error

### ISSUE THREAD

**Issue by ncinar** [mopub/mopub-android-mediation#211] opened 2019-10-30 10:12 UTC
1. **What is the issue?**
     >Admob OAuth Login Error
Admob Mediation Error. I have tried many times but the error continues. I cleared browser history data. I followed several instructions but didn't.
2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x ] I searched https://developers.mopub.com/ and found no answer.
    - [ x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Everything
    * **Platform** (*Android, iOS, Unity*)
        >Android
    * **Observed behavior**
        > OAuth Error: 200, { "access_token": "", "expires_in": 3600, "refresh_token": "", "scope": "", "token_type": "Bearer" }
    * **Expected behavior** (if known)
        > Expected to be successful
    * **Evidence** (if available)
        > ![admob hata2](https://user-images.githubusercontent.com/3996865/67849369-8a065080-fb17-11e9-8ed5-f90693037c93.jpg)

**Comment by ncinar** [comment] 2019-10-30 18:51
Thank you. I'll wait for the correction

**Comment by chauduyphanvu** [comment] 2019-11-04 20:59
@ncinar, the issue is now resolved in production. Please try again and you should be able to re-authenticate.

**Closed by chauduyphanvu** 2019-11-04 20:59 UTC

**Comment by ncinar** [comment] 2019-11-04 21:06
Issue Solved, thanks

**Comment by CodeMaschineX** [comment] 2020-04-10 15:52
Same error happens today, I'm not able to link accounts with admob.
OAuth Error: 200... 
Identical error from first post.
