### ISSUE TITLE
[com.mopub.mobileads.UnityAdsAdapterConfiguration][initializeNetwork] Adapter UnityAdsAdapterConfiguration Log - Unity Ads initialization not started. Context is not an Activity. Note that initialization on the first app launch is a no-op.

### ISSUE THREAD

**Issue by wbj1022** [mopub/mopub-android-mediation#289] opened 2020-09-08 09:36 UTC
In AdapterConfigurationManager#initialize, param is context.getApplicationContext(), 
```
AsyncTasks.safeExecuteOnExecutor(
                new AdapterConfigurationsInitializationAsyncTask(context.getApplicationContext(),
                        adapterConfigurationClasses, networkMediationConfigurations,
                        moPubRequestOptions, this));
```
but in UnityAdsAdapterConfiguration, need activity type
```
else if (configuration != null && context instanceof Activity) {
                    UnityRouter.initUnityAds(configuration, (Activity)context);
                    networkInitializationSucceeded = true;
                } else {
                    MoPubLog.log(AdapterLogEvent.CUSTOM, new Object[]{ADAPTER_NAME, "Unity Ads initialization not started. Context is not an Activity. Note that initialization on the first app launch is a no-op."});
                }
```
An error will occur:
```
I/MoPub:[com.mopub.mobileads.UnityAdsAdapterConfiguration][initializeNetwork] Adapter UnityAdsAdapterConfiguration Log - Unity Ads initialization not started. Context is not an Activity. Note that initialization on the first app launch is a no-op.
I/MoPub:[com.mopub.common.AdapterConfigurationManager][onNetworkInitializationFinished] SDK Log - class com.mopub.mobileads.UnityAdsAdapterConfiguration initialized with error code Native Network or ad adapter was configured incorrectly.
```

**Comment by chauduyphanvu** [comment] 2020-09-08 13:12
Duplicate of https://github.com/mopub/mopub-android-mediation/issues/188.

**Closed by chauduyphanvu** 2020-09-08 13:12 UTC
