### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError Issues after  -

### ISSUE THREAD

**Issue by Armen101** [mopub/mopub-android-mediation#162] opened 2019-05-14 07:41 UTC
com.mopub.mobileads.FacebookAdapterConfiguration.refreshBidderToken (FacebookAdapterConfiguration.java:97)
--
  | com.mopub.mobileads.FacebookAdapterConfiguration.getBiddingToken (FacebookAdapterConfiguration.java:42)
  | com.mopub.common.AdapterConfigurationManager.getTokensAsJsonObject (AdapterConfigurationManager.java:127)
  | com.mopub.common.AdapterConfigurationManager.getTokensAsJsonString (AdapterConfigurationManager.java:107)
  | com.mopub.common.MoPub.getAdvancedBiddingTokensJson (MoPub.java:254)

**Comment by chauduyphanvu1** [comment] 2019-05-14 14:09
@Armen101, friendly reminder to please fill out the[ issue template](https://github.com/mopub/mopub-android-sdk/blob/master/.github/ISSUE_TEMPLATE.md) so we have all the details we need to investigate the issue.

Which versions of the MoPub SDK, Facebook Audience Network SDK, and the corresponding adapters are you using at the time of the crash?  How many ad requests are you making at a given time on average (or at the time of the crash)? Since it's an OOM crash, it seems something might be getting called too often. Since the last known method is getBiddingToken(), which is invoked for each ad request, my assumption is there might too many token JSON objects lying around in memory.

Vu Chau
MoPub SDK Team

**Comment by dba-droid** [comment] 2019-05-20 08:14
Hi Vu Chau, Mopub sdk version is "5.6.0", adapters -
 'com.mopub.mediation:adcolony:3.3.9.0'
 'com.mopub.mediation:facebookaudiencenetwork:5.3.0.0'
 'com.mopub.mediation:admob:17.2.0.1'
 'com.mopub.mediation:tapjoy:12.2.0.3'
 'tv.teads.sdk.android:mopubadapter:4.2.3'
 'com.mopub.mediation:vungle:6.3.24.2'
 We use waterfall technology, and a request within a second can be up to 9 times  (with different  unit ID)

**Comment by Armen101** [comment] 2019-05-20 08:33
Hi Vu Chau!  Sorry it took me so long to get back to you! 
Mopub sdk version - 5.6.0
Adapters -  'com.mopub.mediation:adcolony:3.3.9.0'
'com.mopub.mediation:facebookaudiencenetwork:5.3.0.0'
'com.mopub.mediation:admob:17.2.0.1'
'com.mopub.mediation:tapjoy:12.2.0.3'
'com.mopub.mediation:vungle:6.3.24.2'

We use Waterfall technology, and requests can be up to 9 times per second.

**Comment by chauduyphanvu1** [comment] 2019-06-07 14:16
Closing due to irreproducibility. Feel free to re-open if needed.

**Closed by chauduyphanvu1** 2019-06-07 14:16 UTC

**Comment by do-current** [comment] 2020-09-29 09:36
Still happening on `com.facebook.android:audience-network-sdk:5.9.0`
<img width="1144" alt="Screenshot 2020-09-29 at 2 34 07 PM" src="https://user-images.githubusercontent.com/56651169/94541364-f1b1a800-0260-11eb-8d9f-1733e048573a.png">

**Comment by chauduyphanvu** [comment] 2020-09-29 13:43
@do-current, could you upgrade to one of the newer [Facebook SDK versions](https://github.com/mopub/mopub-android-mediation/blob/master/FacebookAudienceNetwork/CHANGELOG.md) we have certified and let us know if this issue persists? Thanks!
