### ISSUE TITLE
Admob NullPointerException

### ISSUE THREAD

**Issue by aiversonwk** [mopub/mopub-android-mediation#97] opened 2018-11-05 01:59 UTC
Some crashes have occurred in recent days, here are some crash stacks：

```
java.lang.NullPointerException: 
  at com.mopub.mobileads.GooglePlayServicesRewardedVideo$2.run (GooglePlayServicesRewardedVideo.java:178)
  at android.os.Handler.handleCallback (Handler.java:815)
  at android.os.Handler.dispatchMessage (Handler.java:104)
  at android.os.Looper.loop (Looper.java:207)
  at android.app.ActivityThread.main (ActivityThread.java:5728)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:888)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:749)
```

**Comment by aiversonwk** [comment] 2018-11-05 02:00
mopub sdk 5.2.0

**Comment by chauduyphanvu1** [comment] 2018-11-05 02:02
Could you confirm the versions of the adapter and the Mobile Ads (AdMob) SDK you are integrating? Do you have the steps and/or a mini sample app to reproduce that crash? Also, how are you integrating the MoPub SDK?

**Comment by aiversonwk** [comment] 2018-11-05 02:28
here's my gradle code: 
```
implementation 'com.mopub.mediation:admob:17.0.0.0'
implementation 'com.google.android.gms:play-services-ads:17.0.0'
```

I don't have a demo at the moment. These errors are recorded in the google console. About 90 users per hour are affected by this issue. I will try to restore the problem, but I am not sure that it will succeed.

**Comment by chauduyphanvu1** [comment] 2018-11-05 16:02
Thanks for the details. There hasn't been any rewarded video code adapter for the AdMob adapters since your integrated version (https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/CHANGELOG.md), so this might be an isolated issue. 

Are you integrating via Unity or natively in Android? Looking at the line referenced (https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/com/mopub/mobileads/GooglePlayServicesRewardedVideo.java#L178) from the crash, we added logic to ensure that the `isLoaded()` call runs on the main thread for Google at the transition from Unity to Android. It's not expected that it'd crash for you in either case, but I think it's crashing because `mRewardedVideoAd` is null. Again that's not expected, but we'll look into adding a null check there. If you integrate our adapters via source code, you can also do the same in the meantime to prevent this crash.

**Comment by dravyan** [comment] 2018-11-05 21:29
This issue is fixed in https://github.com/mopub/mopub-android-mediation/commit/b20b27125539c62e8b1bc08f7e4e8c0c9d31d07e. Let us know if you still see the issue.

**Closed by dravyan** 2018-11-05 21:29 UTC

**Comment by aiversonwk** [comment] 2018-11-14 01:54
This problem seems to be solved, but in the else code block below, should it be changed together?
```
AdRequest adRequest = builder.build();
if(mRewardedVideoAd) mRewardedVideoAd.loadAd(mAdUnitId, adRequest);
```
At the same time, should we increase the logic when the mRewardedVideoAd variable is null?

**Comment by chauduyphanvu1** [comment] 2018-11-14 04:36
Thanks for letting us know it solved the issue! As for further reinforcing nullability check, we paused all work on the repository (until the end of November) so here's a quick patch you can apply: https://github.com/chauduyphanvu1/mopub-android-mediation/commit/5f22d71e0d4d1ece59d41c27d8f08fb4f7dda91a#diff-6646a99baa46221fc86e44badd3a471d.
