### ISSUE TITLE
Crash with MoPub 5.13.0 Vungle 1.2.3

### ISSUE THREAD

**Issue by LongLostPenPal** [mopub/mopub-android-mediation#272] opened 2020-07-04 04:45 UTC
1. **What is the issue?**
    > My App Crash with MoPub 5.13.0 Vungle 1.2.3 Unity 2019.2.21f

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ ] I searched https://developers.mopub.com/ and found no answer.
    - [ ] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ ] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Provide the data here
    * **Platform** (*Android, iOS, Unity*)
        > Provide the data here
    * **MoPub SDK Version**
        > Provide the data here
    * **Mediation SDK Name & Version**
        > Provide the data here
    * **Mediation Adapter Version**
        > Provide the data here
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Provide the data here
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.

`2020-07-04 12:35:05.769 13383-13437/? I/QarthLog: [PatchStore] create disable file for com.funtriolimited.slots.casino.free uid is 10376
2020-07-04 12:35:05.771 1401-1875/? E/InputDispatcher: Window handle recents_animation_input_consumer has no registered input channel
2020-07-04 12:35:05.775 2270-2507/? I/AppManager: dependence has been existed:13383 -> 23430
2020-07-04 12:35:05.775 676-1214/? W//system/bin/netd: A binder object at 0x726a41a680 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
    
    --------- beginning of crash
2020-07-04 12:35:05.777 13383-13437/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.funtriolimited.slots.casino.free, PID: 13383
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mopub/mobileads/CustomEventRewardedVideo$CustomEventRewardedVideoListener;
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.mopub.common.util.Reflection.instantiateClassWithEmptyConstructor(Reflection.java:158)
        at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:216)
        at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:182)
        at android.os.AsyncTask$3.call(AsyncTask.java:389)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 
     Caused by: java.lang.ClassNotFoundException: com.mopub.mobileads.CustomEventRewardedVideo$CustomEventRewardedVideoListener
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at com.mopub.common.util.Reflection.instantiateClassWithEmptyConstructor(Reflection.java:158) 
        at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:216) 
        at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:182) 
        at android.os.AsyncTask$3.call(AsyncTask.java:389) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 
2020-07-04 12:35:05.777 13383-13456/? I/Unity: ResetResolution  get screen width 1510 height: 720
2020-07-04 12:35:05.777 13383-13456/? I/chatty: uid=10376(com.funtriolimited.slots.casino.free) UnityMain identical 4 lines
2020-07-04 12:35:05.777 13383-13456/? I/Unity: ResetResolution  get screen width 1510 height: 720
2020-07-04 12:35:05.778 1401-1401/? D/HwConnectivityManagerImpl: getNetworkPolicyFlag flagStr null
2020-07-04 12:35:05.779 1401-13618/? I/QarthDisFileCreator: pattern not match
2020-07-04 12:35:05.779 1401-13620/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2020-07-04 12:35:05.780 13383-13438/? I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.funtriolimited.slots.casino.free#10376#0
2020-07-04 12:35:05.780 13383-13438/? I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
2020-07-04 12:35:05.780 13383-13456/? I/Unity: Firebase Analytics API Initializing
2020-07-04 12:35:05.780 13383-13456/? I/Unity: analytics API Initialized
2020-07-04 12:35:05.780 13383-13456/? I/Unity: Firebase Cloud Messaging API Initialized
2020-07-04 12:35:05.781 13383-13438/? I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.funtriolimited.slots.casino.free#10376#256
2020-07-04 12:35:05.781 13383-13438/? I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
2020-07-04 12:35:05.782 1401-3102/? W/ActivityManager: Process com.funtriolimited.slots.casino.free has crashed too many times: killing!
2020-07-04 12:35:05.782 1401-13623/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
`

It Also Crash with MoPub 5.13.0 Vungle 1.1.0
thanks you

**Comment by dravyan** [comment] 2020-07-06 17:41
@LongLostPenPal, thank you for reaching out. With MoPub SDK v5.13.0+, you need to use the latest unitypackage for Vungle [1.2.3](url). Anything lower than 1.2.3 is not compatible with SDK v5.13.0+.
We are not able to reproduce the crash with unitypackage 1.2.3 and SDK 5.13.0. Could you please test with [our sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app) and share the steps and adunit to reproduce the issue?

Thanks,
MoPub Team

**Comment by LongLostPenPal** [comment] 2020-07-07 07:42
> @LongLostPenPal, thank you for reaching out. With MoPub SDK v5.13.0+, you need to use the latest unitypackage for Vungle [1.2.3](url). Anything lower than 1.2.3 is not compatible with SDK v5.13.0+.
> We are not able to reproduce the crash with unitypackage 1.2.3 and SDK 5.13.0. Could you please test with [our sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app) and share the steps and adunit to reproduce the issue?
> 
> Thanks,
> MoPub Team

I test with your sample app ,It works fine in Unity 2019.2 , but my project still crash when
 `[MoPub-Unity] [InitializeSdk] SDK initialization started`
log :
`2020-07-07 15:40:29.867 6603-6677/? I/Unity: [MoPub-Unity] [InitializeSdk] SDK initialization started
2020-07-07 15:40:29.869 1279-27865/? I/DebugKeepScreenOn: setHoldScreenLocked newHoldScreen:Session{5c534a5 6603:u0a10393} currentHoldScreen:null wakeLockState:false
2020-07-07 15:40:29.869 1279-27865/? I/DebugKeepScreenOn: Acquiring screen wakelock due to Window{522b129 u0 com.funtriolimited.slots.casino.free/com.trophit.MyUnityPlayerActivity}
2020-07-07 15:40:29.869 1279-1469/? D/InputDispatcher: set iaware game mode : 16
2020-07-07 15:40:29.872 6603-6677/? I/Unity: ResetResolution  get screen width 1510 height: 720
2020-07-07 15:40:29.876 2272-2362/? I/AppManager: dependence has been existed:6603 -> 9419
2020-07-07 15:40:29.880 6603-6677/? V/com.facebook.unity.FB: SetUserAgentSuffix(Unity.7.18.1)
2020-07-07 15:40:29.881 6603-6677/? V/com.facebook.unity.FB: Init({"appId":"2308573832750831"})
2020-07-07 15:40:29.881 6603-6677/? D/com.facebook.unity.FB: KeyHash: JrtvzfjdTrcuBrsv6g5YzbGmx1Q=
2020-07-07 15:40:29.881 6603-6677/? V/com.facebook.unity.FB: sending to Unity OnInitComplete({"key_hash":"JrtvzfjdTrcuBrsv6g5YzbGmx1Q=\n"})
2020-07-07 15:40:29.882 6603-6677/? I/Unity: Using Facebook Unity SDK v7.18.1 with FBAndroidSDK/5.13.0
2020-07-07 15:40:29.884 6603-6677/? I/Unity: ResetResolution  get screen width 1510 height: 720
2020-07-07 15:40:29.885 6603-6677/? I/Unity: ResetResolution  get screen width 1510 height: 720
2020-07-07 15:40:29.885 6603-6658/? I/QarthLog: [PatchStore] createDisableExceptionQarthFile
2020-07-07 15:40:29.885 6603-6658/? I/QarthLog: [PatchStore] create disable file for com.funtriolimited.slots.casino.free uid is 10393
2020-07-07 15:40:29.888 674-1195/? W//system/bin/netd: A binder object at 0x75a7693d00 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
2020-07-07 15:40:29.889 2272-2362/? I/AppManager: dependence has been existed:6603 -> 9419
2020-07-07 15:40:29.889 1279-1279/? D/HwConnectivityManagerImpl: getNetworkPolicyFlag flagStr null
2020-07-07 15:40:29.891 6603-6677/? I/Unity: ResetResolution  get screen width 1510 height: 720
    
    
    --------- beginning of crash
2020-07-07 15:40:29.892 6603-6658/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.funtriolimited.slots.casino.free, PID: 6603
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mopub/mobileads/CustomEventRewardedVideo$CustomEventRewardedVideoListener;
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.mopub.common.util.Reflection.instantiateClassWithEmptyConstructor(Reflection.java:158)
        at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:216)
        at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:182)
        at android.os.AsyncTask$3.call(AsyncTask.java:389)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 
     Caused by: java.lang.ClassNotFoundException: com.mopub.mobileads.CustomEventRewardedVideo$CustomEventRewardedVideoListener
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at com.mopub.common.util.Reflection.instantiateClassWithEmptyConstructor(Reflection.java:158) 
        at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:216) 
        at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:182) 
        at android.os.AsyncTask$3.call(AsyncTask.java:389) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 
2020-07-07 15:40:29.892 6603-6677/? I/chatty: uid=10393(com.funtriolimited.slots.casino.free) UnityMain identical 4 lines
2020-07-07 15:40:29.892 6603-6677/? I/Unity: ResetResolution  get screen width 1510 height: 720
2020-07-07 15:40:29.892 2272-2362/? I/AppManager: dependence has been existed:6603 -> 9419
2020-07-07 15:40:29.892 1279-6861/? I/QarthDisFileCreator: pattern not match
2020-07-07 15:40:29.894 6603-6677/? I/Unity: Firebase Analytics API Initializing
2020-07-07 15:40:29.894 6603-6677/? I/Unity: analytics API Initialized
2020-07-07 15:40:29.894 6603-6677/? I/Unity: Firebase Cloud Messaging API Initialized
2020-07-07 15:40:29.894 6603-6677/? I/Unity: Received Registration Token: dHJf4ZQ8ER4:APA91bGhRC6vFMjxI7RJARAt6n661J6m2jCO5jdXk18V-mwfIvbci6oNVmQRO-4h-9i4E118he2nkM0J-oLcR7lCQqPz2sl6hgmdD_JHiXG-6_Jt6TkBQF2oiwXTPnruPitd0QK4LMb2
2020-07-07 15:40:29.895 1279-6862/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2020-07-07 15:40:29.901 1279-1791/? E/InputDispatcher: Window handle WindowManager has no registered input channel
2020-07-07 15:40:29.901 1279-6867/? I/QarthDisFileCreator: pattern not match
2020-07-07 15:40:29.902 674-1195/? W//system/bin/netd: A binder object at 0x75a7693d00 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
2020-07-07 15:40:29.902 1279-28019/? W/ActivityTaskManager:   finishTopCrashedActivityLocked Force finishing activity com.funtriolimited.slots.casino.free/com.trophit.MyUnityPlayerActivity
2020-07-07 15:40:29.902 674-1195/? W//system/bin/netd: A binder object at 0x75a7693d00 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
2020-07-07 15:40:29.903 1279-28019/? V/ActivityTaskManager: positionChild stackId=0 to top.
2020-07-07 15:40:29.903 1279-28019/? I/HwMultiWindowSplitUI: removeSplit
2020-07-07 15:40:29.903 1279-1429/? I/HwMultiWindowSplitUI: mCoverLp is null
`

**Comment by dravyan** [comment] 2020-07-08 20:04
@LongLostPenPal , From the above stack trace it seems like your project still having some legacy code `CustomEventRewardedVideo` - `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mopub/mobileads/CustomEventRewardedVideo$CustomEventRewardedVideoListener`. This class does not exist in the 5.13.0 release. Could you share your project zip or sample project zip where we can reproduce the issue?

The below log is coming from our SDK and it is just an `Info` log and not a crash. You will see this log when our SDK attempts to initialize [supported network ](https://developers.mopub.com/publishers/mediation/supported-mediation-partners/#mopub-mediation-integration-tool)adapters and those adapters are not integrated. 
`[com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask][doInBackground] SDK Log With Throwable - Unable to find class com.mopub.mobileads.TapjoyAdapterConfiguration, java.lang.ClassNotFoundException: com.mopub.mobileads.TapjoyAdapterConfiguration`

Thanks,
MoPub Team

**Comment by LongLostPenPal** [comment] 2020-07-09 05:33
> reproduce

[MyProject](https://github.com/LongLostPenPal/MyPackage/raw/master/MoPub_Crash5.13.0.unitypackage)

Thank you very much~

**Comment by dravyan** [comment] 2020-07-09 22:20
@LongLostPenPal, I tried to launch the project you shared and notice that you are still on Vungle unitypackage `1.1.1`. Can you try upgrading it to `1.2.3` which has the adapter version 6.5.3.0 which is compatible with 5.13.0 SDK?

-MoPubTeam

**Comment by LongLostPenPal** [comment] 2020-07-14 12:39
I remove all MoPub ,and reimport new version 5.13.1 , It run well . and my app crashed when i install new facebook audience network ,  [log](https://github.com/mopub/mopub-unity-sdk/issues/132#issuecomment-656630805)

**Comment by chauduyphanvu** [comment] 2020-07-14 13:23
@LongLostPenPal, thanks for letting us know! We are aware of the crash with the Facebook Audience Network SDK. We are working with their team on resolving it—stay tuned!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment] 2020-07-28 13:22
Closing as the Facebook crashes were resolved. Please open a new thread if you see any issues with the Vungle adapters. Thank you!

**Closed by chauduyphanvu** 2020-07-28 13:22 UTC
